"""
Create file using a .aka file

.aka files are created by latex documents using

\usepackage{tocloft}

\newcommand{\listlinkname}{List of Links}
\newlistof{links}{aka}{\listlinkname}
\cftpagenumbersoff{links}
\newcommand{\theaka}{\url{https://aka.klawr.de/project\#\thelinks}}
\newcommand{\aka}[1]{\refstepcounter{links}\theaka%
\addcontentsline{aka}{links}{%
\theaka\dotfill\hbox{}\newline%
\makebox[\textwidth][s]{\dotfill\url{#1}}}}

where the project in the \theaka command has to be the name of the directory in this repo.
The mappings are generated by calling links with

\aka{https://github.com/klawr/aka}

The index.html in the respective repo has to be updated of course. 
"""

import re

first_half = """
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>srp links</title>
</head>

<body>
    <div id='links'>
        <h3><a id='project_page' href='https://github.com/klawr/deepmech/tree/master/reports/srp'>Project Page</a></h3>
        <p>To be redirected via URL hash activate JavaScript</p>
        <ol>"""
	
second_half = """
        </ol>
    </div>

    <script>
        const hash = window.location.hash;
        let a;
        if (hash) {
            a = document.getElementById(hash);
        }
        if (!a) {
            a = document.getElementById('project_page')
        }
        if (a) {
            document.getElementById('links').style.display = 'none';
            const text = document.createElement('h3');
            text.innerHTML = `You are being redirected to: ${a.href}`;
            document.body.appendChild(text);
            setTimeout(() => { a.click(); }, 1000);
        }
    </script>
</body>

</html>
"""

aka_path = input('Path to .aka file: ')

def list_entry(id, link):
    return """
            <li>
                <a id='%s' href='%s'>
                    %s
                </a>
            </li>""" % (id, link, link)

with open(aka_path) as aka:
    m = re.findall(r'\\url\s*{(https:\/\/\S[^}]+)}', aka.read())
    a = m[0:len(m):2]
    b = m[1:len(m):2]

    h = first_half
    
    for i in range(len(a)):
        h += list_entry(a[i], b[i])

    h += second_half

    with open('index.html', 'w') as html:
        html.write(h)
	
